Repository LEEJAE-GO/auto-write, pull requests merged in 2023-05, with the labels that each got.

#1 add : 스프링 프로젝트 초기설정
  backend/.gitignore
  backend/build.gradle
  backend/gradle/wrapper/gradle-wrapper.jar
  backend/gradle/wrapper/gradle-wrapper.properties
  backend/gradlew
  backend/gradlew.bat
  backend/settings.gradle
  backend/src/main/java/com/backend/backend/BackendApplication.java
  backend/src/main/java/com/backend/backend/Controller/MainController.java
  backend/src/main/resources/application.properties
  backend/src/test/java/com/backend/backend/BackendApplicationTests.java
Labels: good first issue

#5 add : 리액트 프로젝트 셋팅
  frontend/index.html
  frontend/package.json
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/assets/utils.js
  frontend/src/components/RouterLink.jsx
  frontend/src/index.css
  frontend/src/layouts/Footer.jsx
  frontend/src/layouts/Header.jsx
  frontend/src/layouts/Main.jsx
  frontend/src/main.jsx
  frontend/src/pages/BookStore.jsx
  frontend/src/pages/Home.jsx
  frontend/src/pages/Login.jsx
  frontend/src/pages/Maker.jsx
  frontend/src/pages/NotFound.jsx
  frontend/yarn.lock
Labels: add

#4 docs : backend.md 수정
  desc/backend.md
Labels: docs

#6 add : notFound 페이지 추가
  frontend/src/layouts/Main.jsx
  frontend/src/pages/NotFound.jsx
Labels: add
